[workspace]
authors = ["Michael Booth <michael@databooth.com.au>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "Mojo-workloads"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
 test-gpu = "mojo src/test_gpu.mojo"
 stencil-bench = "mojo 7-point-stencil/Mojo/laplacian.mojo"
 stencil-cpu-bench = "mojo benchmarks/stencil_cpu.mojo"
 babel-bench = "mojo babelStream/Mojo/babelStream.mojo"
 bude-bench = "mojo miniBUDE/Mojo/miniBUDE.mojo"
 hf-bench = "mojo hartree-fock/Mojo/hartree-fock.mojo"

[dependencies]
mojo = ">=0.26.2.0.dev2026012705,<0.27"
python = "3.11.*"
