[workspace]
authors = ["Michael Booth <michael@databooth.com.au>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "Mojo-workloads"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.2.0.dev2026012705,<0.27"
